# Generated by Django 4.1 on 2022-08-31 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('usuariouser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fPrestamo', models.DateTimeField()),
                ('fDevolucion', models.DateTimeField()),
                ('estado', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Prestamo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranportista', models.CharField(max_length=30)),
                ('idTracking', models.CharField(max_length=30)),
                ('tipoEnvio', models.CharField(max_length=30)),
                ('fEstimada', models.DateField()),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Prestamo.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
                ('calle2', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('cPostal', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Prestamo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descuentos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Prestamo.pedido')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CarritodeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Prestamo.cliente')),
            ],
        ),
    ]
